apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploy.deployName }}
spec:
  replicas: {{ .Values.deploy.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploy.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploy.name }}
    spec:
      containers:
        - name: {{ .Values.deploy.name }}
          image: {{ .Values.deploy.container.image }} 
          imagePullPolicy: {{ .Values.deploy.container.imagePullPolicy }}  
