apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
spec:
  selector:             
    app: {{ .Values.service.name }}
  ports:
  - name: {{ .Values.service.name }}
    protocol: TCP
    port: {{ .Values.service.port }}     
    targetPort: {{ .Values.service.port }}     
